/*
 * ULTRASONIC_Configurations.h
 *
 *  Created on: Jun 27, 2023
 *      Author: User
 */

#ifndef INCLUDE_HAL_ULTRASONIC_ULTRASONIC_CONFIGURATIONS_H_
#define INCLUDE_HAL_ULTRASONIC_ULTRASONIC_CONFIGURATIONS_H_

#define    ULTRSONIC_PIN PIN4
#define    ULTRSONIC_PORT PORTD


#endif /* INCLUDE_HAL_ULTRASONIC_ULTRASONIC_CONFIGURATIONS_H_ */
