/*
 * WDT_Configurations.h
 *
 *  Created on: Jun 20, 2023
 *      Author: User
 */

#ifndef INCLUDE_MCAL_WDT_WDT_CONFIGURATIONS_H_
#define INCLUDE_MCAL_WDT_WDT_CONFIGURATIONS_H_

/*
Choose Prescaler :-
    WDT_PRESCALER_16K
    WDT_PRESCALER_32K
    WDT_PRESCALER_64K
    WDT_PRESCALER_128K
    WDT_PRESCALER_256K
    WDT_PRESCALER_512K
    WDT_PRESCALER_1024K
    WDT_PRESCALER_2048K 
*/
#define WDT_PRESCALER WDT_PRESCALER_2048K

#endif /* INCLUDE_MCAL_WDT_WDT_CONFIGURATIONS_H_ */
