/*
 * LCD4_Configuration.c
 *
 *  Created on: Oct 14, 2022
 *      Author: User
 */

#ifndef INCLUDE_HAL_LCD4_LCD4_CONFIGURATION_H_
#define INCLUDE_HAL_LCD4_LCD4_CONFIGURATION_H_

#define LCD_ROW_ONE 1
#define LCD_ROW_TWO 2

#define LCD_DATA_PORT    PORTD
#define LCD_CONTROL_PORT PORTC


#define RS_PIN PIN0
#define RW_PIN PIN1
#define E_PIN  PIN2

/*
Options:-
    ONE_LINE
    TWO_LINE
*/
#define LCD_LINE_NO TWO_LINE

/*
Options:-
    DOTS_5_7
    DOTS_5_10
*/
#define LCD_FONT_ DOTS_5_7_

/*
Options:-           (FOR DD RAM)
    DISPLAY_OFF
    DISPLAY_ON
*/
#define DISPLAY_STATUS DISPLAY_ON

/*
Options:- 
    CURSOR_OFF
    CURSOR_ON
*/
#define CURSOR_STATUS CURSOR_ON

/*
Options:-
    CURSOR_BLANK_OFF
    CURSOR_BLANK_ON 
*/
#define CURSOR_BLANK_STATUS CURSOR_BLANK_ON

/*
Options:-
    ID_DECREASE
    ID_INCREASE
*/
#define ID_STATUS ID_INCREASE

/*
Options:-
    SHIFT_DISPLAY_OFF
    SHIFT_DISPLAY_ON
*/
#define SHIFT_DISPLAY SHIFT_DISPLAY_OFF

#define FUNCTION_SET1 0b00100000
#define FUNCTION_SET2 0b00100000
#define FUNCTION_SET3 CONC_BIT(LCD_LINE_NO,LCD_FONT_,0,0,0,0,0,0)

#define ON_OFF_CONTROL1 0b00000000
#define ON_OFF_CONTROL2 CONC_BIT(1,DISPLAY_STATUS,CURSOR_STATUS,CURSOR_BLANK_STATUS,0,0,0,0)

#define DISPLAY_CLEAR1 0b00000000
#define DISPLAY_CLEAR2 0b00010000

#define ENTRY_MODE_SET1 0b00000000 
#define ENTRY_MODE_SET2 CONC_BIT(0,1,ID_STATUS,SHIFT_DISPLAY,0,0,0,0)


#endif /* INCLUDE_HAL_LCD4_LCD4_CONFIGURATION_H_ */
