/*
 * TIMER0_Configurations.h
 *
 *  Created on: Dec 4, 2022
 *      Author: User
 */

#ifndef INCLUDE_MCAL_TIMER0_TIMER0_CONFIGURATIONS_H_
#define INCLUDE_MCAL_TIMER0_TIMER0_CONFIGURATIONS_H_



#endif /* INCLUDE_MCAL_TIMER0_TIMER0_CONFIGURATIONS_H_ */
