/*
 * TIMER0_Configurations.h
 *
 *  Created on: Dec 4, 2022
 *      Author: User
 */

#ifndef INCLUDE_MCAL_TIMER0_TIMER0_CONFIGURATIONS_H_
#define INCLUDE_MCAL_TIMER0_TIMER0_CONFIGURATIONS_H_
/*
choose timer Mode:-
    TIMER0_NORMAL_MODE   
    TIMER0_PWM_MODE      
    TIMER0_CTC_MODE      
    TIMER0_FAST_PWM_MODE 
*/
#define TIMER0_MODE TIMER0_NORMAL_MODE 

/*
choose prescaler:-
    TIMER0_NO_CLK          
    TIMER0_NO_PRESCALER    
    TIMER0_PRESCALER_8     
    TIMER0_PRESCALER_64    
    TIMER0_PRESCALER_256   
    TIMER0_PRESCALER_1024  
    TIMER0_EXT_CLK_FALLING 
    TIMER0_EXT_CLK_RISING  
*/
#define TIMER0_CLK_MODE TIMER0_PRESCALER_8


#endif /* INCLUDE_MCAL_TIMER0_TIMER0_CONFIGURATIONS_H_ */
